apiVersion: v1
kind: PersistentVolume
metadata:
  name: datafiles
  labels:
    name: datafiles
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/datafiles